Web/MyPosCR.Web/Controllers/DashboardController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using MyPosCR.Data;
using MyPosCR.Web.Models.Dashboard;

namespace MyPosCR.Web.Controllers.Dashboard
{
    public class DashboardController : Controller
    {
        private readonly ApplicationDbContext db;
        public DashboardController(ApplicationDbContext db)
        {
            this.db = db;
        }

        [Authorize(Roles = "Administrator")]
        public IActionResult Index()
        {
            var viewModel = new IndexViewModel();
            var users = this.db.Users.Select(u => new IndexUserViewModel
            {
                Username = u.UserName,
                PhoneNumber = u.PhoneNumber,
                Credits = u.Credits
            }).ToList();
            viewModel.Users = users;

            return View(viewModel);
        }
    }
}

Web/MyPosCR.Web/Controllers/TransactionsController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using myPosCR.Services;
using myPosCR.Services.Models;
using MyPosCR.Data;
using MyPosCR.Web.Models.Transactions;

namespace MyPosCR.Web.Controllers
{
    [Authorize]
    public class TransactionsController : Controller
    {
        private readonly ITransactionsService TransactionsService;
        private readonly IApplicationUserService ApplicationUserService;
        private readonly ApplicationDbContext db;

        public TransactionsController(ITransactionsService transactionsService, IApplicationUserService applicationUserService, ApplicationDbContext db)
        {
            this.TransactionsService = transactionsService;
            this.ApplicationUserService = applicationUserService;
            this.db = db;
        }

        //public IActionResult Index()
        //{
        //    return View();
        //}

        public IActionResult Index()
        {
            var viewModel = new IndexViewModel();
            var users = new List<IndexTransactionViewModel>();

            if (this.User.IsInRole("Administrator"))
            {
                users = this.db.Transactions.Select(t => new IndexTransactionViewModel
                {
                    TransactionId = t.TransactionId,
                    Sender = t.Sender,
                    Reciever = t.Reciever,
                    Amount = t.Amount,
                    Message = t.Message,
                    Date = t.Date
                }).ToList();
            }
            else
            {
                users = this.db.Transactions.Where(t => t.Sender.Email == User.Identity.Name || t.Reciever.Email == User.Identity.Name).Select(t => new IndexTransactionViewModel
                {
                    TransactionId = t.TransactionId,
                    Sender = t.Sender,
                    Reciever = t.Reciever,
                    Amount = t.Amount,
                    Message = t.Message,
                    Date = t.Date
                }).ToList();
            }
            viewModel.Transactions = users;

            return View(viewModel);
        }

        public IActionResult Details(int id)
        {
            var transaction = this.TransactionsService.GetById(id);

            if (transaction == null)
            {
                return this.NotFound();
            }

            return View(transaction);
        }

        public IActionResult Create()
        {
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> Create(TransactionListingServiceModel input)
        {
            input.Date = DateTime.UtcNow;
            input.SenderEmail = HttpContext.User.Identity.Name;

            var sender = this.ApplicationUserService.GetByEmail(input.SenderEmail);

            ModelState.Remove("SenderEmail");
            ModelState.Remove("RecieverEmail");
            ModelState.Remove("SenderPhoneNumber");

            if (ModelState.IsValid)
            {
                try
                {
                    if (sender.PhoneNumber == input.RecieverPhoneNumber)
                    {
                        throw new Exception("You cannot make transactions to your account.");
                    }
                    if (sender.Credits < input.Amount)
                    {
                        throw new Exception("You do not have enough credits.");
                    }
                    int transactionId = await this.TransactionsService.CreateAsync(input);

                    return this.RedirectToAction(nameof(this.Details), new { id = transactionId });
                }
                catch (Exception err)
                {
                    //return view and display err.Message
                    return View(input);
                    throw;
                }
            }
            else
            {
                return View(input);
            }
        }
    }
}


//var transaction = new Transaction
//{
//    Sender = transactionData.Sender,
//    Reciever = transactionData.Reciever,
//    Amount = transactionData.Amount,
//    Message = transactionData.Message,
//    Date = transactionData.Date
//};
////firstName,
////middleName,
////lastName,
////(int)clas,
////(int)numberInClass,
////$"{DateTime.UtcNow.Year}/{DateTime.UtcNow.Year + 1}",
////enrollmentDate,
////status.ToString(),
////DateTime.UtcNow);

//this.data.Transactions.Add(transaction);

//this.data.SaveChanges();

Web/MyPosCR.Web/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - MyPosCR.Web</title>
    <link rel="stylesheet" href="~/lib/favico.js/favico-0.3.10.min.js">
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/MyPosCR.Web.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-dark bg-dark border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">MyPosCR</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-light" asp-area="" asp-controller="Dashboard" asp-action="Index">Users</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-light" asp-area="" asp-controller="Transactions" asp-action="Index">Transactions</a>
                        </li>
                    </ul>
                    <partial name="_LoginPartial" />
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>
    
   @*<footer class="border-top footer text-light">
        <div class="container">
            &copy; 2022 - MyPosCR.Web
        </div>
    </footer>*@

    <footer class="border-top footer bg-dark text-center text-white">
     @* <!-- Grid container -->
      <div class="container p-4 pb-0">
        <!-- Section: Social media -->
        <section class="mb-4">
          <!-- Facebook -->
          <a class="btn btn-outline-light btn-floating m-1" href=""https://www.facebook.com/profile.php?id=100009588433228"" role="button"
            ><i class="fab fa-facebook-f"></i
          ></a>

          <!-- Instagram -->
          <a class="btn btn-outline-light btn-floating m-1" href="https://www.instagram.com/hristova__viktoria/" role="button"
            ><i class="fab fa-instagram"></i
          ></a>

          <!-- Linkedin -->
          <a class="btn btn-outline-light btn-floating m-1" href="https://www.linkedin.com/in/viktoriq-hristova-091502200/" role="button"
            ><i class="fab fa-linkedin-in"></i
          ></a>

          <!-- Github -->
          <a class="btn btn-outline-light btn-floating m-1" href="https://github.com/hristova23" role="button"
            ><i class="fab fa-github"></i
          ></a>
        </section>
      </div>*@

      <!-- Copyright -->
      <div class="text-center p-3" style="background-color: rgba(0, 0, 0, 0.2);">
            &copy; 2022 - MyPosCR
        @*<a class="text-white" href="/">myPosCR.com</a>*@
      </div>
      <!-- Copyright -->
    </footer>
    
    <script src="~/lib/favico.js/favico-0.3.10.min.js"></script>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>